# 2D Numpy

In [1]:
# Import the libraries 

import numpy as np
import matplotlib.pyplot as plt


In [2]:
# Create list 

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array 
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# Numpy array dimensions

A.ndim

2

In [5]:
#Numpy array shape

A.size

9

# Accessing different elements of a Numpy Array 

In [6]:
# Access the element on the second row and third column 

A[1, 2]

23

In [8]:
# Or 

A[1][2]

23

In [9]:
A [0][0]

11

In [10]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [13]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

# Basic Operations 

In [15]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [17]:
# Create a numpy array Y
Y = np.array ([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [19]:
# Add X & Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [20]:
#Numpy Array Y
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [21]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [22]:
# Element wise product

#Array Y
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [23]:
#Array X
X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [24]:
# Multiply X & Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [25]:
# Matrix multiplication

#Matrix A

A = np.array([[0, 1, 1], [1, 0 ,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [26]:
#Matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [27]:
# Dot product

Z = np.dot(A, B)
Z

array([[0, 2],
       [0, 2]])

In [28]:
# Sine of Z
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [29]:
# Matrix C

C = np.array ([[1, 1], [2, 2], [3, 3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [30]:
# C transposed

C.T

array([[1, 2, 3],
       [1, 2, 3]])